### PR TITLE
SSU support for OTA on SaraU210 module

### PR DESCRIPTION
**Pull request by Rocketct**
Added API for write and read from sara module to retrive file during OTA's
procedure

cc:/ @manchoz

### CODE REVIEW

**Comment by Rocketct** [comment]
ok i'll revome from SFU and implement SSU  :smiley:

**Comment by Rocketct** [comment]
done, are missing only the examples i will add when will be available and after merge, (and remove the white space added in ->boot/binary)

**Comment by manchoz** [comment]
@aentinger @Rocketct 

I have updated also the examples here https://github.com/manchoz/ArduinoCore-samd/tree/manchoz_test_ssu/libraries/SSU/examples.

There are also a few minor changes to [SSUBoot.ino](https://github.com/manchoz/ArduinoCore-samd/blob/a2478d91224e8e4f179acfa35e603243640d4bd6/libraries/SSU/extras/SSUBoot/SSUBoot.ino#L68) because I have refactored [`GSMFileUtils::begin()`](https://github.com/manchoz/MKRGSM/blob/93fc09cdf83936642ec46e53b1849aa42267f7a3/src/GSMFileUtils.h#L10).

**Comment by manchoz** [comment]
@aentinger 

> LGTM 👍 I wish there would be a rename functionality though ... but I've understood there is none?

You are right; there is no rename functionality, unfortunately.

An alternative implementation would be appending the OTA header (or just the CRC) to the end of the file and check for its presence in SSUBoot.ino. WDYT?

**Comment by fabltd** [comment]
Hi

Is there any docs on loading the file into the GSM file system ?

Regards - Jeremy

On 25 Jun 2020, at 11:26, Giampaolo Mancini <notifications@github.com>
wrote:

﻿

@aentinger <https://github.com/aentinger>

LGTM 👍 I wish there would be a rename functionality though ... but I've
understood there is none?

You are right; there is no rename functionality, unfortunately.

An alternative implementation would be appending the OTA header (or just
the CRC) to the end of the file and check for its presence in SSUBoot.ino.
WDYT?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arduino/ArduinoCore-samd/pull/534#issuecomment-649453188>,
or unsubscribe

**Comment by manchoz** [comment]
Hi @fabltd,
You can find an example of how to do it manually here [SSU_LoadBinary.ino](https://github.com/arduino/ArduinoCore-samd/blob/f4e8cabc6c8fefe6cdd8a31a9c00d648016a2341/libraries/SSU/examples/SSU_LoadBinary/SSU_LoadBinary.ino).

A full example with HTTP download will be published in the coming days.

**Comment by fabltd** [comment]
Thanks

Where will the example be published ?

Regards,
Jeremy Turner

On 25 Jun 2020, at 13:31, Giampaolo Mancini <notifications@github.com>
wrote:

﻿

Hi @fabltd <https://github.com/fabltd>,
You can find an example of how to do it manually here SSU_LoadBinary.ino
<https://github.com/arduino/ArduinoCore-samd/blob/f4e8cabc6c8fefe6cdd8a31a9c00d648016a2341/libraries/SSU/examples/SSU_LoadBinary/SSU_LoadBinary.ino>
.

A full example with HTTP download will be published in the coming days.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arduino/ArduinoCore-samd/pull/534#issuecomment-649511401>,
or unsubscribe

**Comment by manchoz** [comment]
@fabltd here, alongside the other SSU examples. I will notify you when ready.

**Comment by aentinger** [comment]
Hi @manchoz and @Rocketct :wave: Is this PR complete and tested? If so please let me know because I shall merge it in then.

**Comment by manchoz** [comment]
@aentinger, yes, both complete and tested even by a third party.

**Comment by manchoz** [comment]
@fabltd, [SSU_HttpOta.ino](https://github.com/arduino/ArduinoCore-samd/blob/970877baa8eb17466be781682e7bfbb96c65a261/libraries/SSU/examples/SSU_HttpOta/SSU_HttpOta.ino) will be merged soon.

Please, read the usage notes carefully.

**Comment by fabltd** [comment]
Thanks

QQ - What does SSU mean?

Also https://www.arduino.cc/en/Reference/SSU is a dead link.

**Pull request merged**
