### PR TITLE
Add method to automatically retrieve sketch start

### PR DESCRIPTION
**Pull request by facchinm**
Superseded #184

If `ARDUINO_SAMD_VARIANT_COMPLIANCE` is >= 1.6.10 you should define ` __text_start__ ` symbol in the linker script (as in the examples). This allows `APP_START` variable to automatically acquire the right position.

Another possible improvement is checking if APP_START == 0, which means that `without_bootloader` linker script was used. In this case, calling `banzai` should be avoided and a simple restart should be performed.

@awatterott @sandeepmistry @cmaglie

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Don't forget to update `VARIANT_COMPLIANCE_CHANGELOG` if we decide to merge this.

Also, if the linker scripts are the same for all the variants maybe we consolidate them later?

**Comment by awatterott** [comment]
@facchinm Thanks. I will test it at the weekend.
BOSSA will also need some changes to work with different bootloader sizes: https://github.com/shumatech/BOSSA/issues/33
As workaround for BOSSA it is possible to check if the first write address is smaller than the bootloader size and then use it as an offset. 
```
if first_write_address < bootloader_size
  offset = bootloader_size - first_write_address

real_write_address = write_address + offset
```

**Comment by awatterott** [comment]
@facchinm I have tested the changes and everything works.
We will also release our bootloader (sam-ba + mass-storage) in the next days: https://github.com/watterott/SAM-BAR

**Comment by tuxedo0801** [comment]
@awatterott 
this might be offtopic, but: is there already some info about your upcoming bootloader already online?!

**Comment by awatterott** [comment]
@tuxedo0801 It is a SAM-BA compatible bootloader with an integrated 2nd mass-storage bootloader and it fits in 16k.

**Comment by tuxedo0801** [comment]
Sounds great. Looking forward for more details.

**Pull request merged**
