### PR TITLE
Fix async serial port operation at 1200 baud, fix flush, fix data bits.

### PR DESCRIPTION
**Pull request by TomKeddie**
Fix https://github.com/arduino/ArduinoCore-samd/issues/84 operation at 1200 baud.

Fix https://github.com/arduino/ArduinoCore-samd/issues/83 for data widths other than 8 bits.

Fix https://github.com/arduino/ArduinoCore-samd/issues/82 to make flush semantics match AVR.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@TomKeddie thanks for submitting! The changes look good.

I've proposed #86 as an alternative to https://github.com/TomKeddie/ArduinoCore-samd/commit/103ddee889529da6da1a5b16d466e3f99df7677e. It changes UART configuration to use asynchronous fractional mode.

**Comment by TomKeddie** [comment]
I think https://github.com/arduino/ArduinoCore-samd/pull/86 is better.  Having floating point code in the base libraries should be avoided wherever possible.  You should commit and then I will pull and clean up my change.

**Comment by cmaglie** [comment]
@TomKeddie
#86 is now merged, would you like to update this pr?

Alternatively I can cherry pick the reminder of this PR, just tell me.

**Comment by TomKeddie** [comment]
@cmaglie if you have the time to cherry pick I'd appreciate it.  Thanks, Tom

**Comment by cmaglie** [comment]
rebased and merged. Thanks!

**Pull request closed without merging**
