### PR TITLE
Update Wire peripheral handler

### PR DESCRIPTION
**Pull request by stonehippo**
The existing onService method for I2C peripheral (slave) implementation
swapped the sense of onRequest (master read) and onReceive (master
write) handlers. It also didn't handle writes correctly, requiring two
write operations to get bytes out of the buffer and in the onReceive
handler.

This implementation follows the SERCOM I2C flow defined for the
default clock-stretching case (CTRLB.SCLSM=0) as described in the
SAMD21 datasheet.

### CODE REVIEW

**Comment by stonehippo** [comment]
I found a couple of issues that I've resolved, namely that NACKs needed to be sent at the end of the read or write logic to close down the connection. Should be all set now.

I'm using a version of this code locally to test out a custom peripheral and so far, it's working as expected (with the NACK fix in place).

**Comment by stonehippo** [comment]
I've found bug here (the write NACK prevents reads). I'll fix that and push a revision to the PR.

**Comment by stonehippo** [comment]
Ok, last bug (that I've found) smooshed. Would love a review of this and to see it get merged in.

**Comment by reufer** [comment]
works for me!

**Pull request closed without merging**
