### PR TITLE
Provide irq safe implementation of RingBuffer

### PR DESCRIPTION
**Pull request by facchinm**
Alternative way to fix https://github.com/arduino/ArduinoCore-samd/issues/580 without restoring the buggy RingBuffer implementation from API

### CODE REVIEW

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @facchinm :rocket:

**Review by matthijskooijman — APPROVED** [review]
Code also looks good to me.

I wonder: Is this class something that should live in -API? I can imagine that this code is moved to API, and then individual cores make available a "sync.h" that -API can use to get platform-specific "synchronized" behaviour. As an added bonus, this would mean that `synchronized` can become a nice and portable way to disable interrupts (though I wonder if `synchronized` is the perfect name, but I guess it's modeled after Java, right?).

**Comment by facchinm** [comment]
Yes, it's modeled over Java and could have a more embedd-ish name if we decide to port it to -API :slightly_smiling_face: . 
The problem in doing so is that we must ask for a `sync.h` or similar to be present in the core implementation, and given the include order (`Arduino.h` depends on `ArduinoAPI.h`) so we can't easily do feature discovery via defines.
So, I'd merge it here as a reference implementation and then we can discuss in API repo to give it a broader scope.

**Comment by matthijskooijman** [comment]
> The problem in doing so is that we must ask for a sync.h or similar to be present in the core implementation,

Well, you could just require that a core that uses -API supplies a working `sync.h`, right?

>  So, I'd merge it here as a reference implementation and then we can discuss in API repo to give it a broader scope.

Agreeed.

**Pull request merged**
