### PR TITLE
[bl] Allowing USB VID customization

### PR DESCRIPTION
**Pull request by aethaniel**
This patch allows USB VID customization via the compiler command line:

See line #78 of Makefile:
CFLAGS_EXTRA?=-D__SAMD21G18A__ -DUSB_PID_HIGH=0x00 -DUSB_PID_LOW=0x4D -DUSB_VID_LOW=0x41 -DUSB_VID_HIGH=0x23

I have added two more macros in order to have bootloaders ported on non-Arduino boards
These macros are used in sam_ba_usb.c in descriptor initialization, same way as for USB PID previously done.

Signed-off-by: Thibaut VIARD <aethaniel@sam-geek.org>

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@aethaniel changes to define and use ```USB_PID_LOW``` and ```USB_VID_HIGH``` look good.

Are the updates to ```MODULE_PATH``` and ```T``` in the Makefile needed as well?

**Comment by aethaniel** [comment]
Yes, everything is needed to match IDE v1.7
Thanks for reviewing
T.

On 21 January 2016 23:48:14 CET, Sandeep Mistry <notifications@github.com> wrote:
>@aethaniel changes to define and use ```USB_PID_LOW``` and
>```USB_VID_HIGH``` look good.
>
>Are the updates to ```MODULE_PATH``` and ```T``` in the Makefile needed
>as well?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arduino/ArduinoCore-samd/pull/72#issuecomment-173740466

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by sandeepmistry** [comment]
Thanks, I think you mean't IDE 1.6.7 right?

I've merged and then removed the sections for IDE 1.6.5 in the Makefile (https://github.com/arduino/ArduinoCore-samd/commit/5f9b54b436baed82e62d3f13d43997f7ccab959c), as this core requires IDE 1.6.6 or later anyways.

**Comment by aethaniel** [comment]
Yes, sorry for the typo, was indeed 1.6.7

On 22 January 2016 15:30:33 CET, Sandeep Mistry <notifications@github.com> wrote:
>Thanks, I think you mean't IDE 1.6.7 right?
>
>I've merged and then removed the sections for IDE 1.6.5 in the Makefile
>(https://github.com/arduino/ArduinoCore-samd/commit/5f9b54b436baed82e62d3f13d43997f7ccab959c),
>as this core requires IDE 1.6.6 or later anyways.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arduino/ArduinoCore-samd/pull/72#issuecomment-173935462

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Pull request merged**
