### PR TITLE
Add USB send timeout

### PR DESCRIPTION
**Pull request by sandeepmistry**
This change adds a 70 millisecond timeout on USB sends.

Related to one of the problems in https://github.com/arduino-libraries/WiFi101/issues/72#issuecomment-230262218. On Windows, if you open and close the Serial Monitor with a sketch that uses `SerialUSB.println(...)` the entire sketch will hang.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @RamonRibes,

Could you please tryout this build with the following sketch. Then open and close the Serial Monitor in the IDE. The LED should continue to blink after you do so.

```arduino
void setup() {
  Serial.begin(9600);
  Serial.println("hello");

  pinMode(6, OUTPUT);
}

void loop() {
  Serial.println("LED HIGH");
  digitalWrite(6, HIGH);
  delay(1000);

  Serial.println("LED LOW");
  digitalWrite(6, LOW);
  delay(1000);
}
```

**Comment by RamonRibes** [comment]
Test procedure:
-Arduino IDE 1.6.9 (new installation on a Windows 10 **new** PC).
-Loaded standard SAMD boards library.
-Selected MKR1000.
-Compiled&started your sketch (Serial monitor kept closed).
-The built-in led does as intended.
-After 12 minutes, i opened the serial monitor. Led is doing OK. Monitor shows messages.
-After 12 minutes, i closed the serial monitor. Led remains in HIGH state. 
-------------------------------------------------------------------------------------------------------------
-Build Pull Request #152 as instructed.
-Selected MKR1000 from Pull Request #152.
-Compiled&started your sketch (Serial monitor kept closed).
-The built-in led does as intended.
-After 12 minutes, i opened the serial monitor. Led is doing OK. Monitor shows messages.
-After 12 minutes, i closed the serial monitor. Led remains switching on/off each second.
-After 12 minutes, i re-opened the serial monitor. Led is doing OK. Monitor shows messages again.
...so the patch is working OK!
Congratulations! :-)

**Comment by sandeepmistry** [comment]
@RamonRibes great news!

So there is a solution for 1/3 problems you are facing so far.

**Comment by sandeepmistry** [comment]
Closing this now in favour of #154.

**Pull request closed without merging**
