### PR TITLE
[bootloader] [test needed] Bootloader leds activity

### PR DESCRIPTION
**Pull request by aethaniel**
This PR brings:
- activity LEDs support
- Genuino Zero build
- Arduino IDE 1.6.6 (MSWin specific change in APPDATA from Roaming to Local)

Readme.md updated with added 'how-to build' section.

I currently have a problem with my laptop which is refusing to mount properly the Arduino Zero.
Help is needed to verify the LED activity behaviour :-)

### CODE REVIEW

**Comment by facchinm** [comment]
@ArduinoBot build this please

**Comment by AloyseTech** [comment]
Error when trying to upload the bootloader from 1.6.6 with atmel ICE.
Error when trying to program the zero again : 

/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/hardware" -hardware "/Users/TheoMeyer/Library/Arduino15/packages" -tools "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/hardware/tools/avr" -tools "/Users/TheoMeyer/Library/Arduino15/packages" -built-in-libraries "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/libraries" -libraries "/Users/TheoMeyer/Documents/Arduino/libraries" -fqbn=arduino:samd:arduino_zero_native -vid-pid=0X2341_0X804D -ide-version=10606 -build-path "/var/folders/v6/tj3__g0x16gfgz5vmcx385s80000gn/T/build6d4dfa44b4b978531c5b7578e36f2b24.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/examples/01.Basics/Blink/Blink.ino"
/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/hardware" -hardware "/Users/TheoMeyer/Library/Arduino15/packages" -tools "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/hardware/tools/avr" -tools "/Users/TheoMeyer/Library/Arduino15/packages" -built-in-libraries "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/libraries" -libraries "/Users/TheoMeyer/Documents/Arduino/libraries" -fqbn=arduino:samd:arduino_zero_native -vid-pid=0X2341_0X804D -ide-version=10606 -build-path "/var/folders/v6/tj3__g0x16gfgz5vmcx385s80000gn/T/build6d4dfa44b4b978531c5b7578e36f2b24.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/Applications/Arduino/1.6.6/Arduino.app/Contents/Java/examples/01.Basics/Blink/Blink.ino"
Attention: platform.txt du cœur 'Arduino SAMD (32-bits ARM Cortex-M0+) Boards' contiens recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}" dépassé, converti automatiquement en recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". La mise a niveau de ce cœur est conseillée.
Attention: platform.txt du cœur 'SAMD Pull request #64 (Build 43)' contiens recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}" dépassé, converti automatiquement en recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". La mise a niveau de ce cœur est conseillée.
ATTENTION : La catégorie '' dans la bibliothèque OneWire n'est pas valide. Définition sur : 'Uncategorized'
ATTENTION : La catégorie '' dans la bibliothèque UIPEthernet n'est pas valide. Définition sur : 'Uncategorized'
"/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=48000000L -DARDUINO=10606 -DARDUINO_SAMD_ZERO -DARDUINO_ARCH_SAMD  -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x804d -DUSBCON '-DUSB_MANUFACTURER="Arduino LLC"' '-DUSB_PRODUCT="Arduino Zero"' "-I/Users/TheoMeyer/Library/Arduino15/packages/arduino/hardware/samd/1.6.2/cores/arduino" "-I/Users/TheoMeyer/Library/Arduino15/packages/arduino/hardware/samd/1.6.2/variants/arduino_zero" "/var/folders/v6/tj3__g0x16gfgz5vmcx385s80000gn/T/build6d4dfa44b4b978531c5b7578e36f2b24.tmp/sketch/Blink.ino.cpp"
fork/exec /bin/arm-none-eabi-g++: no such file or directory
Erreur lors de la compilation.


It seems that when I installed this build, it removed the arm-none-eabi from the main samd package in Arduino15/package/......

**Comment by AloyseTech** [comment]
@aethaniel It works now : I only copied the bootloader directories and replace the 1.6.2 one by yours. Thanks for the update, it's great to see those leds blink while uploading! The led blinking is so fast that it looks like they are always on though.

**Comment by aethaniel** [comment]
Great! 
Thanks for testing this 'new' feature!

On 13 November 2015 20:32:14 CET, AloyseTech <notifications@github.com> wrote:
>@aethaniel It works now : I only copied the bootloader directories and
>replace the 1.6.2 one by yours. Thanks for the update, it's great to
>see those leds blink while uploading! The led blinking is so fast that
>it looks like they are always on though.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arduino/ArduinoCore-samd/pull/64#issuecomment-156535946

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by sandeepmistry** [comment]
Just tried this out, after I burn the new bootloader the RX LED is alway lit (although dim). I'll look into using a similar approach to #121.

**Comment by cmaglie** [comment]
Superseded by #165

**Pull request closed without merging**
