### PR TITLE
Read Internal Temperature

### PR DESCRIPTION
**Pull request by mitchellpontague**
Add method to read the internal temperature of the device using the built-in ADC channel of SAMD devices.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @mitchellpontague,

Thanks for taking the time to submit this pull request!

I'm not sure if this new functionality should be contained in the core. What you you think about making a new Arduino library (SAMD specific) for it?

**Comment by cmaglie** [comment]
I'd also love to see a library, it could be also made multi-architecure/multi-board using the boards/architecture defines.

**Comment by Adminius** [comment]
@mitchellpontague hi, can you make a library for that? or do you need help for it?

**Comment by sabas1080** [comment]
I require this feature and I have created a library based in the work of @mitchellpontague , welcome feedback  https://github.com/ElectronicCats/ElectronicCats_InternalTemperatureZero

Thanks @mitchellpontague

**Comment by mitchellpontague** [comment]
Thanks @sabas1080 , looks good to me.

**Pull request closed without merging**
