### PR TITLE
Add feature for decompressing LZSS compressed binary files by second stage bootloader SSU

### PR DESCRIPTION
**Pull request by aentinger**
If the files `UPDATE.BIN.LZSS` and `UPDATE.OK` are present the SSU will decompress `UPDATE.BIN.LZSS` using the LZSS algorithm and write it's content to the flash. This change goes together with https://github.com/arduino-libraries/ArduinoIoTCloud/pull/168 .

@manchoz care to review?

### CODE REVIEW

**Comment by manchoz** [comment]
LGTM.

Tested with an updated `SSU_LZSS_HttpOta` sketch. I also have an `lzss.dylib` to contribute.

**Comment by aentinger** [comment]
Thank you. Can you directly commit into this PR or shall I merge and you'll be opening separate PRs?

**Comment by manchoz** [comment]
I don't have write permissions. Let's merge and I will rebase and open a separate PR.

**Comment by aentinger** [comment]
Here you go @manchoz :+1:

**Pull request merged**
