### PR TITLE
Limit max SPI clock frequency to F_CPU/2

### PR DESCRIPTION
**Pull request by facchinm**
Fixes https://github.com/arduino/ArduinoCore-samd/issues/576

### CODE REVIEW

**Review by aentinger — APPROVED** [review]
LGTM :+1:

**Comment by matthijskooijman** [comment]
What's the exact problem here? Does something overflow when the SPI speed > F_CPU/2? Where does this limit come from exactly? IMHO the code and commit message could use a bit more details for future reference.

**Comment by facchinm** [comment]
@matthijskooijman agree, this is the direct porting of https://github.com/arduino/ArduinoCore-samd/blob/1.8.9/libraries/SPI/SPI.h#L40-L46 (which was not merged during API migration).
I'll add some info to the commit message

**Review by giulcioffi — APPROVED** [review]

**Comment by matthijskooijman** [comment]
Thanks for updating the commit message, looks good to me. I do see that one testcase failed, was that already failing on master?

**Comment by facchinm** [comment]
It's failing due to rate limiting :sweat_smile: Everything should be fine

**Pull request merged**
